package youbook.model;

public class Author {
	
	int authorId;
	String name;
	Book book;
	
	// This constructor can be used for reading records from MySQL, where we have all fields
	// including the authorId
	public Author(int authorId, String name, Book book) {
		this.authorId = authorId;
		this.name = name;
		this.book = book;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have 
	// the authorId, such as a foreign key reference to authorId.
	// Given authorId, we can fetch the full Author record.
	public Author(int authorId) {
		this.authorId = authorId;
	}
	
	// This constructor can be used for creating new records, where the authorId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Author(String name, Book book) {
		this.name = name;
		this.book = book;
	}

	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name =name;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}
	
}
