package youbook.model;

public class Book {
	
	int bookId;
	String title;
	String publisherName;
	String publicationYear;
	
	// This constructor can be used for reading records from MySQL, where we have all fields
	// including the bookId
	public Book(int bookId, String title,
	            String publisherName, String publicationYear) {
		this.bookId = bookId;
		this.title = title;
		this.publisherName = publisherName;
		this.publicationYear = publicationYear;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have 
	// the bookId, such as a foreign key reference to bookId.
	// Given bookId, we can fetch the full Book record.
	public Book(int bookId) {
		this.bookId = bookId;
	}

	// This constructor can be used for creating new records, where the bookId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Book(String title, String publisherName, String publicationYear) {
		this.title = title;
		this.publisherName = publisherName;
		this.publicationYear = publicationYear;
	}

	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

	public String getPublicationYear() {
		return this.publicationYear;
	}

	public void setPublicationYear(String publicationYear) {
		this.publicationYear = publicationYear;
	}
}
