package youbook.model;

public class Payment {

	protected int paymentId;
	protected User user;
	protected PaymentType paymentType;
	public enum PaymentType {CREDIT_CARD,PAYPAL}
	protected double totalAmount;
	
	// This constructor can be used for reading records from MySQL, where we have all fields
	// including paymentId.
	public Payment (int paymentId, User user, PaymentType paymentType, double totalAmount) {
		this.paymentId = paymentId;
		this.user = user;
		this.paymentType = paymentType;
		this.totalAmount = totalAmount;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have 
	// the paymentId, such as a foreign key reference to paymentId.
	// Given paymentId, we can fetch the full Payment record.
	public Payment (int paymentId) {
		this.paymentId = paymentId;
	}
	
	// This constructor can be used for creating new records, where the paymentId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Payment(User user, PaymentType paymentType, double totalAmount) {
		this.user = user;
		this.paymentType = paymentType;
		this.totalAmount = totalAmount;
	}
	
	public int getPaymentId() {
		return this.paymentId;
	}
	
	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}
	
	public User getUser() {
		return this.user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public PaymentType getPaymentType() {
		return this.paymentType;
	}
	public void setPaymentType(PaymentType paymentType) {
		this.paymentType = paymentType;
	}
	public double getTotalAmount() {
		return this.totalAmount;
	}
	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}
}
