package youbook.model;

public class Review {
	
	protected int reviewId;
	protected User user;
	protected Book book;
	protected double rating;
	protected String comment;
	
	// This constructor can be used for reading records from MySQL, where we have all fields
	// including the reviewId.
	public Review(int reviewId, User user, Book book, double rating, String comment) {
		this.reviewId = reviewId;
		this.user = user;
		this.book = book;
		this.rating = rating;
		this.comment = comment;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have 
	// the reviewId, such as a foreign key reference to reviewId.
	// Given reviewId, we can fetch the full Review record.
	public Review (int reviewId) {
		this.reviewId = reviewId;
	}
	
	// This constructor can be used for creating new records, where the reviewId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Review(User user, Book book, double rating, String comment) {
		this.user = user;
		this.book = book;
		this.rating = rating;
		this.comment = comment;
	}
	
	
	public int getReviewId() {
		return this.reviewId;
	}
	
	public void setReviewId(int reviewId) {
		this.reviewId = reviewId;
	}
	
	public Book getBook() {
		return this.book;
	}
	
	public void setBook(Book book) {
		this.book = book;
	}
	
	public User getUser() {
		return this.user;
	}
	
	public void setUser(User user) {
		this.user = user;
	}
	
	public double getRating() {
		return this.rating;
	}
	
	public void setRating(double rating) {
		this.rating = rating;
	}
	
	public String getComment() {
		return this.comment;
	}
	
	public void setComment(String comment) {
		this.comment = comment;
	}
}
