package youbook.model;

public class WishList {
	
    private int wishListId;
    private Book book;
    private User user;
    
	// This constructor can be used for reading records from MySQL, where we have all fields
	// including the wishListId.
    public WishList(int wishListId, Book book, User user) {
    	this.wishListId = wishListId;
    	this.book = book;
    	this.user = user;
    }
    
    // This constructor can be used for reading records from MySQL, where we only have 
    // the wishListId, such as a foreign key reference to wishListId.
 	// Given wishListId, we can fetch the full WishList record.
    public WishList(int wishListId) {
        this.wishListId = wishListId;
    }
    
	// This constructor can be used for creating new records, where the wishListId may not be
	// assigned yet since it is auto-generated by MySQL.
    public WishList(Book book, User user) {
    	this.book = book;
    	this.user = user;
    }

    public int getWishlistId() {
        return this.wishListId;
    }

    public void setWishListId(int wishListId) {
        this.wishListId = wishListId;
    }

    public Book getBook() {
        return this.book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
